[graph]

[graph.figure]
figsize = [6.0, 4.5]
dpi = 100
layout = "tight"

[graph.palettes]
categorical = "Set2"

[graph.spines]
top = false
right = false
bottom = true
left = true

[line]
marker = "o"
linestyle = "-"

[line.errorbar]
capsize = 3.0
fmt = "none"
