[datatables]

  [datatables.xy]
  x_title = "X"
  y_title = "Y"

  [datatables.column]
  x_title = "X"
  y_title = "Y"


[graphs]

  [graphs.axis]

    [graphs.axis.continuous]
    scale = "linear"
    format.linear = "decimal"
    format.log10 = "power10"


[layout]

  [layout.caption]
  direction  = "down"
  pad.top    = 2 
  pad.left   = 12
  pad.right  = 12
  pad.bottom = 2 

    [layout.caption.text]

      [layout.caption.text.h1]
      size = 10
      weight = "bold"
      color = "black"
      linespacing = 1.2
      spacing_before = 4
      spacing_after = 6
      vertical_alignment = "top"
      horizontal_alignment = "left"

      [layout.caption.text.h2]
      size = 8
      weight = "bold"
      color = "black"
      linespacing = 1.2
      spacing_before = 0
      spacing_after = 0
      vertical_alignment = "top"
      horizontal_alignment = "left"
      
      [layout.caption.text.p]
      size = 8
      weight = "regular"
      color = "black"
      linespacing = 1.2
      spacing_before = 0
      spacing_after = 0
      vertical_alignment = "top"
      horizontal_alignment = "left"

      [layout.caption.text.s]
      size = 6
      weight = "regular"
      color = "grey"
      linespacing = 1.2
      spacing_before = 0
      spacing_after = 0
      vertical_alignment = "top"
      horizontal_alignment = "left"

    [layout.caption.line]

      [layout.caption.line.dividing]
      length = 50
      width = 0.5
      color = "#002147"
      spacing_before = 2
      spacing_after = 2

      [layout.caption.line.branding]
      length = 20
      width = 4
      color = "#002147"
      spacing_before = 0
      spacing_after = 6
